### ISSUE TITLE
pipx run resiliparse faild: ModuleNotFoundError: No module named 'joblib'

### ISSUE THREAD

**Issue by MaxPeal** [chatnoir-eu/chatnoir-resiliparse#18]
```
user@box:~$ pipx run resiliparse
Traceback (most recent call last):
  File "/home/user/.local/pipx/.cache/42f25da10f76b98/bin/resiliparse", line 5, in <module>
    from resiliparse.cli import main
  File "/home/user/.local/pipx/.cache/42f25da10f76b98/lib/python3.9/site-packages/resiliparse/cli.py", line 18, in <module>
    from joblib import Parallel, delayed
ModuleNotFoundError: No module named 'joblib'
user@box:~$ pipx install resiliparse
  installed package resiliparse 0.11.1, installed using Python 3.9.2
  These apps are now globally available
    - resiliparse
done! ✨ 🌟 ✨
user@box:~$ resiliparse
Traceback (most recent call last):
  File "/home/user/.local/bin/resiliparse", line 5, in <module>
    from resiliparse.cli import main
  File "/home/user/.local/pipx/venvs/resiliparse/lib/python3.9/site-packages/resiliparse/cli.py", line 18, in <module>
    from joblib import Parallel, delayed
ModuleNotFoundError: No module named 'joblib'
user@box:~$ 
```

**Comment by MaxPeal** [comment]
```
user@box:~$ pipx run --verbose resiliparse
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/home/user/.local/pipx/venvs/pipx/bin/python'
pipx >(needs_upgrade:69): Time since last upgrade of shared libs, in seconds: 1561712. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:172): running /home/user/.local/pipx/.cache/42f25da10f76b98/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run:103): Reusing cached venv /home/user/.local/pipx/.cache/42f25da10f76b98
pipx >(run_subprocess:172): running /home/user/.local/pipx/.cache/42f25da10f76b98/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(exec_app:387): exec_app: /home/user/.local/pipx/.cache/42f25da10f76b98/bin/resiliparse
Traceback (most recent call last):
  File "/home/user/.local/pipx/.cache/42f25da10f76b98/bin/resiliparse", line 5, in <module>
    from resiliparse.cli import main
  File "/home/user/.local/pipx/.cache/42f25da10f76b98/lib/python3.9/site-packages/resiliparse/cli.py", line 18, in <module>
    from joblib import Parallel, delayed
ModuleNotFoundError: No module named 'joblib'
user@box:~$
```

**Comment by phoerious** [comment]
joblib is an optional dependency, that is installed by running `pip install resiliparse[cli]`. There should be a check for this, though.

**Comment by MaxPeal** [comment]
found also some more missing dependencys

```console
(venv) user@box:/tmp/chatnoir-resiliparse$ python3 -m venv venv && source venv/bin/activate
(venv) user@box:/tmp/chatnoir-resiliparse$ pip3 install resiliparse[cli]
Requirement already satisfied: resiliparse[cli] in /tmp/venv/lib/python3.9/site-packages (0.11.1)
Requirement already satisfied: fastwarc==0.11.1 in /tmp/venv/lib/python3.9/site-packages (from resiliparse[cli]) (0.11.1)
Requirement already satisfied: tqdm in /tmp/venv/lib/python3.9/site-packages (from resiliparse[cli]) (4.63.0)
Requirement already satisfied: click in /tmp/venv/lib/python3.9/site-packages (from resiliparse[cli]) (8.0.4)
Collecting joblib
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Installing collected packages: joblib
Successfully installed joblib-1.1.0
(venv) user@box:/tmp/chatnoir-resiliparse$ pip3 install fastwarc
Requirement already satisfied: fastwarc in /tmp/venv/lib/python3.9/site-packages (0.11.1)
Requirement already satisfied: click in /tmp/venv/lib/python3.9/site-packages (from fastwarc) (8.0.4)
Requirement already satisfied: tqdm in /tmp/venv/lib/python3.9/site-packages (from fastwarc) (4.63.0)
(venv) user@box:/tmp/chatnoir-resiliparse$
(venv) user@box:/tmp/chatnoir-resiliparse$ resiliparse html benchmark /tmp/warcs/WARCPROX-20220315191329244-00000-icvgw961.warc 
HTML parser benchmark <title> extraction:
=========================================
Resiliparse (Lexbor):  1 documents in 0.98s (1.02 documents/s) 
[Not benchmarking Selectolax, because it is not installed.
[Not benchmarking BeautifulSoup4, because it is not installed.
(venv) user@box:/tmp/chatnoir-resiliparse$ pip3 install Selectolax BeautifulSoup4
Collecting Selectolax
  Downloading selectolax-0.3.6-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (5.0 MB)
     |████████████████████████████████| 5.0 MB 2.5 MB/s 
Collecting BeautifulSoup4
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.1-py3-none-any.whl (37 kB)
Collecting Cython>=0.29.23
  Using cached Cython-0.29.28-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Installing collected packages: soupsieve, Cython, Selectolax, BeautifulSoup4
Successfully installed BeautifulSoup4-4.10.0 Cython-0.29.28 Selectolax-0.3.6 soupsieve-2.3.1
(venv) user@box:/tmp/chatnoir-resiliparse$ resiliparse html benchmark /tmp/warcs/WARCPROX-20220315191329244-00000-icvgw961.warc 
HTML parser benchmark <title> extraction:
=========================================
Resiliparse (Lexbor):  1 documents in 1.09s (0.92 documents/s) 
Selectolax (Lexbor):   1 documents in 0.88s (1.14 documents/s)
Selectolax (MyHTML):   1 documents in 0.64s (1.56 documents/s)
Traceback (most recent call last):                          
  File "/tmp/venv/bin/resiliparse", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/resiliparse/cli.py", line 147, in benchmark
    BeautifulSoup(bytes_to_str(content, detect_encoding(content)), 'lxml').title
  File "/tmp/venv/lib/python3.9/site-packages/bs4/__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
(venv) user@box:/tmp/chatnoir-resiliparse$ pip3 install Selectolax BeautifulSoup4 lxml
Requirement already satisfied: Selectolax in /tmp/venv/lib/python3.9/site-packages (0.3.6)
Requirement already satisfied: BeautifulSoup4 in /tmp/venv/lib/python3.9/site-packages (4.10.0)
Collecting lxml
  Using cached lxml-4.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Requirement already satisfied: soupsieve>1.2 in /tmp/venv/lib/python3.9/site-packages (from BeautifulSoup4) (2.3.1)
Requirement already satisfied: Cython>=0.29.23 in /tmp/venv/lib/python3.9/site-packages (from Selectolax) (0.29.28)
Installing collected packages: lxml
Successfully installed lxml-4.8.0
(venv) user@box:/tmp/chatnoir-resiliparse$ resiliparse html benchmark /tmp/warcs/WARCPROX-20220315191329244-00000-icvgw961.warc 
HTML parser benchmark <title> extraction:
=========================================
Resiliparse (Lexbor):  1 documents in 1.00s (1.00 documents/s) 
Selectolax (Lexbor):   1 documents in 0.87s (1.15 documents/s)
Selectolax (MyHTML):   1 documents in 0.63s (1.58 documents/s)
BeautifulSoup4 (lxml): 1 documents in 3.16s (0.32 documents/s)  
(venv) user@box:/tmp/chatnoir-resiliparse$ 
```

**Comment by MaxPeal** [comment]
```console
(venv) user@box:/tmp/chatnoir-resiliparse$ resiliparse lang benchmark /tmp/warcs/WARCPROX-20220315191329244-00000-icvgw961.warc 
Skipping FastText benchmark, since no model has been specified.
Skipping langid benchmark, since it is not installed.
Run "pip install langid" to install it.
Traceback (most recent call last):
  File "/tmp/venv/bin/resiliparse", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/resiliparse/cli.py", line 538, in benchmark
    in_data = open(infile, 'r').read().replace('\n', ' ')
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 41278: invalid start byte
(venv) user@box:/tmp/chatnoir-resiliparse$ 
```

**Comment by phoerious** [comment]
> found also some more missing dependencys

Those are conditionally imported only for the benchmark and should not be part of the package dependency spec, but I could create an extra target, I guess.
